USE complaints_management_service;

SELECT * FROM `MANUFACTURING SITE`;

SELECT * FROM CUSTOMER;

SELECT * FROM PRODUCT;

SELECT * FROM ENDUSER;

SELECT * FROM HOSPITAL;

SELECT * FROM SUPPLIER;

SELECT * FROM DISTRIBUTOR;

SELECT * FROM STORES;

SELECT * FROM SELLS;

SELECT * FROM `NON CONFORMANCE REPORT`;

SELECT * FROM COMPLAINT;

SELECT * FROM CUSTOMORDER;

SELECT * FROM SUPPLIES;

SELECT * FROM DISTRIBUTES;

SELECT * FROM REPORTS;

SELECT * FROM ASSIGNED;